algorithm: Clonal Selection Algorithm
author: Sagnik Patra
csa_best_score: 0.9737147791142229
features:
- District_Encoded
- Percentage of Scheduled Caste Population _2001_Rural
- Percentage of Scheduled Caste Population _2001_Urban
- Percentage of Scheduled Caste Population _2001_Total
- Percentage of Scheduled Caste Population _2011_Rural
- Percentage of Scheduled Caste Population _2011_Urban
- Rural_Growth
- Urban_Growth
- Total_Growth
- Rural_Urban_Gap_2001
- Rural_Urban_Gap_2011
- Average_SC_Percentage
- Priority_Score
model_type: Regression
outputs:
  full_dataset_result_csv: C:\Users\NXTWAVE\Downloads\Regional Inclusion Analysis
    System\csa_full_dataset_result.csv
  h5: C:\Users\NXTWAVE\Downloads\Regional Inclusion Analysis System\csa_model.h5
  json: C:\Users\NXTWAVE\Downloads\Regional Inclusion Analysis System\csa_results.json
  pkl: C:\Users\NXTWAVE\Downloads\Regional Inclusion Analysis System\csa_model.pkl
  prediction_csv: C:\Users\NXTWAVE\Downloads\Regional Inclusion Analysis System\csa_prediction.csv
  result_csv: C:\Users\NXTWAVE\Downloads\Regional Inclusion Analysis System\csa_result.csv
  yaml: C:\Users\NXTWAVE\Downloads\Regional Inclusion Analysis System\csa_config.yaml
project: CSA Smart Regional Inclusion Analysis System
target: Percentage of Scheduled Caste Population _2011_Total
